- ros_topic_name: /imu/data
  gz_topic_name: /world/waves/model/blueboat/link/imu_link/sensor/imu_sensor/imu
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS

- ros_topic_name: /gps/fix
  gz_topic_name: /world/waves/model/blueboat/link/gps_link/sensor/navsat_sensor/navsat
  ros_type_name: sensor_msgs/msg/NavSatFix
  gz_type_name: gz.msgs.NavSat
  direction: GZ_TO_ROS

- ros_topic_name: /odometry
  gz_topic_name: /model/blueboat/odometry
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS

- ros_topic_name: /stbd/cmd_thrust
  gz_topic_name: /model/blueboat/joint/motor_stbd_joint/cmd_thrust
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /port/cmd_thrust
  gz_topic_name: /model/blueboat/joint/motor_port_joint/cmd_thrust
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ